name: Compile EaglerForge Client
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Grant Execute Permissions
        run: chmod +x ./build_init.sh ./build_make_workspace.sh ./CompileLatestClient.sh run_chmod.sh

      - name: Initialize Workspace
        run: ./build_init.sh

      - name: Setup Decompiler Workspace
        run: ./build_make_workspace.sh

      - name: Compile Client Base
        run: ./CompileLatestClient.sh --headless || echo "Bypassing GUI Installer"

      - name: Upload HTML Game File
        uses: actions/upload-artifact@v4
        with:
          name: EaglerForge-Offline-Client
          path: |
            ./**/*.html
            ./sources/
